// Direct company job boards used as V1 job sources (launch decision #3):
// Greenhouse, Lever and Ashby public posting APIs only — no aggregators, no
// SerpAPI. Carried over from the prototype's company lists. Slugs that stop
// resolving are skipped (and logged) by ingestion.

export type AtsProvider = 'greenhouse' | 'lever' | 'ashby'

export type CompanyBoard = { provider: AtsProvider; slug: string; company: string }

export const COMPANY_BOARDS: CompanyBoard[] = [
  // greenhouse
  { provider: 'greenhouse', slug: 'stripe', company: 'Stripe' },
  { provider: 'greenhouse', slug: 'shopify', company: 'Shopify' },
  { provider: 'greenhouse', slug: 'airbnb', company: 'Airbnb' },
  { provider: 'greenhouse', slug: 'figma', company: 'Figma' },
  { provider: 'greenhouse', slug: 'notion', company: 'Notion' },
  { provider: 'greenhouse', slug: 'canva', company: 'Canva' },
  { provider: 'greenhouse', slug: 'hubspot', company: 'HubSpot' },
  { provider: 'greenhouse', slug: 'zendesk', company: 'Zendesk' },
  { provider: 'greenhouse', slug: 'twilio', company: 'Twilio' },
  { provider: 'greenhouse', slug: 'datadoghq', company: 'Datadog' },
  { provider: 'greenhouse', slug: 'cloudflare', company: 'Cloudflare' },
  { provider: 'greenhouse', slug: 'hashicorp', company: 'HashiCorp' },
  { provider: 'greenhouse', slug: 'gitlab', company: 'GitLab' },
  { provider: 'greenhouse', slug: 'fastly', company: 'Fastly' },
  { provider: 'greenhouse', slug: 'brex', company: 'Brex' },
  { provider: 'greenhouse', slug: 'ramp', company: 'Ramp' },
  { provider: 'greenhouse', slug: 'plaid', company: 'Plaid' },
  { provider: 'greenhouse', slug: 'gusto', company: 'Gusto' },
  { provider: 'greenhouse', slug: 'lattice', company: 'Lattice' },
  { provider: 'greenhouse', slug: 'checkr', company: 'Checkr' },
  { provider: 'greenhouse', slug: 'adyen', company: 'Adyen' },
  { provider: 'greenhouse', slug: 'wise', company: 'Wise' },
  { provider: 'greenhouse', slug: 'n26', company: 'N26' },
  { provider: 'greenhouse', slug: 'klarna', company: 'Klarna' },
  { provider: 'greenhouse', slug: 'revolut', company: 'Revolut' },
  { provider: 'greenhouse', slug: 'coinbase', company: 'Coinbase' },
  { provider: 'greenhouse', slug: 'gemini', company: 'Gemini' },
  { provider: 'greenhouse', slug: 'chainalysis', company: 'Chainalysis' },
  { provider: 'greenhouse', slug: 'fireblocks', company: 'Fireblocks' },
  { provider: 'greenhouse', slug: 'bitgo', company: 'BitGo' },
  { provider: 'greenhouse', slug: 'anchorage', company: 'Anchorage Digital' },
  { provider: 'greenhouse', slug: 'ripple', company: 'Ripple' },
  { provider: 'greenhouse', slug: 'circle', company: 'Circle' },
  { provider: 'greenhouse', slug: 'alchemy', company: 'Alchemy' },
  { provider: 'greenhouse', slug: 'paxos', company: 'Paxos' },
  { provider: 'greenhouse', slug: 'blockdaemon', company: 'Blockdaemon' },
  { provider: 'greenhouse', slug: 'uniswaplabs', company: 'Uniswap' },
  { provider: 'greenhouse', slug: 'opensea', company: 'OpenSea' },
  { provider: 'greenhouse', slug: 'worldcoin', company: 'Worldcoin' },
  { provider: 'greenhouse', slug: 'elliptic', company: 'Elliptic' },
  { provider: 'greenhouse', slug: 'trmlabs', company: 'TRM Labs' },
  { provider: 'greenhouse', slug: 'consensys', company: 'ConsenSys' },
  { provider: 'greenhouse', slug: 'kraken', company: 'Kraken' },
  { provider: 'greenhouse', slug: 'complyadvantage', company: 'ComplyAdvantage' },
  { provider: 'greenhouse', slug: 'feedzai', company: 'Feedzai' },
  { provider: 'greenhouse', slug: 'unit21', company: 'Unit21' },
  { provider: 'greenhouse', slug: 'sumsub', company: 'Sumsub' },
  { provider: 'greenhouse', slug: 'moonpay', company: 'MoonPay' },
  { provider: 'greenhouse', slug: 'bitstamp', company: 'Bitstamp' },
  { provider: 'greenhouse', slug: 'layerzero', company: 'LayerZero' },
  { provider: 'greenhouse', slug: 'persona', company: 'Persona' },
  { provider: 'greenhouse', slug: 'alloy', company: 'Alloy' },
  { provider: 'greenhouse', slug: 'ebury', company: 'Ebury' },
  // lever
  { provider: 'lever', slug: 'airtable', company: 'Airtable' },
  { provider: 'lever', slug: 'webflow', company: 'Webflow' },
  { provider: 'lever', slug: 'loom', company: 'Loom' },
  { provider: 'lever', slug: 'mercury', company: 'Mercury' },
  { provider: 'lever', slug: 'rippling', company: 'Rippling' },
  { provider: 'lever', slug: 'retool', company: 'Retool' },
  { provider: 'lever', slug: 'linear', company: 'Linear' },
  { provider: 'lever', slug: 'vercel', company: 'Vercel' },
  { provider: 'lever', slug: 'tailscale', company: 'Tailscale' },
  { provider: 'lever', slug: 'deel', company: 'Deel' },
  { provider: 'lever', slug: 'remote', company: 'Remote' },
  { provider: 'lever', slug: 'gocardless', company: 'GoCardless' },
  { provider: 'lever', slug: 'pleo', company: 'Pleo' },
  { provider: 'lever', slug: 'polygon-technology', company: 'Polygon' },
  { provider: 'lever', slug: 'dydx', company: 'dYdX' },
  { provider: 'lever', slug: 'messari', company: 'Messari' },
  { provider: 'lever', slug: 'wintermute-trading', company: 'Wintermute' },
  { provider: 'lever', slug: 'onfido', company: 'Onfido' },
  { provider: 'lever', slug: 'veriff', company: 'Veriff' },
  { provider: 'lever', slug: 'nansen', company: 'Nansen' },
  { provider: 'lever', slug: 'bybit', company: 'Bybit' },
  { provider: 'lever', slug: 'okx', company: 'OKX' },
  // ashby
  { provider: 'ashby', slug: 'anthropic', company: 'Anthropic' },
  { provider: 'ashby', slug: 'openai', company: 'OpenAI' },
  { provider: 'ashby', slug: 'mistral', company: 'Mistral AI' },
  { provider: 'ashby', slug: 'cohere', company: 'Cohere' },
  { provider: 'ashby', slug: 'anyscale', company: 'Anyscale' },
  { provider: 'ashby', slug: 'modal', company: 'Modal' },
  { provider: 'ashby', slug: 'dbt', company: 'dbt Labs' },
  { provider: 'ashby', slug: 'posthog', company: 'PostHog' },
  { provider: 'ashby', slug: 'plane', company: 'Plane' },
  { provider: 'ashby', slug: 'morpho', company: 'Morpho' },
  { provider: 'ashby', slug: 'eigenlayer', company: 'EigenLayer' },
  { provider: 'ashby', slug: 'wormhole', company: 'Wormhole' },
  { provider: 'ashby', slug: 'sardine', company: 'Sardine' },
  { provider: 'ashby', slug: 'hyperliquid', company: 'Hyperliquid' },
  { provider: 'ashby', slug: 'lucinity', company: 'Lucinity' },
]
